/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.gui;

import src.backend.Composition;
import src.backend.Library;

import java.awt.BorderLayout;
import java.awt.Window;
import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author Michael Tu
 */
public class EditFrame extends JPanel 
{
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addButton;
    private JTextField arrangerField;
    private JButton backButton;
    private JTextField composerField;
    private JLabel directions;
    private JLabel titleLabel;
    private JLabel composerLabel;
    private JLabel arrangerLabel;
    private JLabel publisherLabel;
    private JLabel vbodaGradeLabel;
    private JLabel notesLabel;
    private JTextArea notesTextArea;
    private JTextField publisherField;
    private JTextField titleField;
    private JTextField vbodaGradeField;
    private JScrollPane sp;

    private static Library library; //Create a general object
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form EditFrame
     */
    
    
    public EditFrame(Library l) {
        initComponents(l);
    }

    public EditFrame(Library l, Composition c, int index, boolean ifAdd)
    {
        vfComponents(l, c, index, ifAdd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Library l) {

        directions = new JLabel();
        titleLabel = new JLabel();
        titleField = new JTextField();
        composerLabel = new JLabel();
        composerField = new JTextField();
        arrangerLabel = new JLabel();
        arrangerField = new JTextField();
        publisherLabel = new JLabel();
        publisherField = new JTextField();
        vbodaGradeField = new JTextField();
        vbodaGradeLabel = new JLabel();
        notesTextArea = new JTextArea();
        notesLabel = new JLabel();
        addButton = new JButton();
        backButton = new JButton();
        sp = new JScrollPane(notesTextArea, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        JPanel editFrame = this;

        library = l;

        directions.setHorizontalAlignment(SwingConstants.CENTER);
        directions.setText("Enter information below to add a composition.");

        titleLabel.setText("Title:");

        titleField.setText("");
        titleField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }

            private void titleFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
                // TODO add your handling code here:
            }//GEN-LAST:event_titleFieldActionPerformed
        });

        composerLabel.setText("Composer:");
        composerField.setText("");

        arrangerLabel.setText("Arranger: ");
        arrangerField.setText("");

        publisherLabel.setText("Publisher:");
        publisherField.setText("");

        vbodaGradeLabel.setText("VBODA Grade: ");
        vbodaGradeField.setText("0");

        notesLabel.setText("Notes:");
        notesTextArea.setText("");
        notesTextArea.setLineWrap(true);
        notesTextArea.setWrapStyleWord(true);      

        addButton.setText("Add");
        addButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
                    addButtonActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            private void addButtonActionPerformed(ActionEvent evt) throws Exception
            {
                if(Integer.parseInt(vbodaGradeField.getText()) < 0 || Integer.parseInt(vbodaGradeField.getText()) > 6)
                {
                    JOptionPane.showMessageDialog(editFrame, "Invalid input", "ERROR", JOptionPane.ERROR_MESSAGE);
                    vbodaGradeField.setText("0");
                }

                else
                {
                    Composition c = new Composition(titleField.getText(),
                                                        composerField.getText(),
                                                        arrangerField.getText(),
                                                        publisherField.getText(),
                                                        Integer.parseInt(vbodaGradeField.getText()),
                                                        notesTextArea.getText());
                    library.append(c);
                    library.sortByTitle();
            
                    EditSummaryFrame esFrame = new EditSummaryFrame(c, library);
                    JFrame frame = new JFrame("EditConfirmationFrame");
            
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.getContentPane().add(esFrame, BorderLayout.CENTER);
                    frame.pack();
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                }
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                backButtonActionPerformed(evt);
            }

            private void backButtonActionPerformed(ActionEvent evt) 
            {
                JComponent comp = (JComponent)evt.getSource();
                Window win = SwingUtilities.getWindowAncestor(comp);
                win.dispose();
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(directions))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(vbodaGradeLabel)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vbodaGradeField, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(notesLabel)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sp, GroupLayout.PREFERRED_SIZE, 363, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(composerLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(composerField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(titleLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(titleField, GroupLayout.PREFERRED_SIZE, 371, GroupLayout.PREFERRED_SIZE))))
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(arrangerLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(arrangerField, GroupLayout.PREFERRED_SIZE, 345, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(publisherLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(publisherField, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(directions)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(composerLabel)
                    .addComponent(composerField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(arrangerLabel)
                    .addComponent(arrangerField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(publisherLabel)
                    .addComponent(publisherField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(vbodaGradeLabel)
                    .addComponent(vbodaGradeField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabel)
                    .addComponent(sp, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(backButton))
                .addContainerGap())
        );
    }

    private void vfComponents(Library l, Composition edit, int index, boolean ifAdd) { // ifAdd = true (append the metadata); ifAdd = false (replace an existing composition)

        directions = new JLabel();
        titleLabel = new JLabel();
        titleField = new JTextField();
        composerLabel = new JLabel();
        composerField = new JTextField();
        arrangerLabel = new JLabel();
        arrangerField = new JTextField();
        publisherLabel = new JLabel();
        publisherField = new JTextField();
        vbodaGradeField = new JTextField();
        vbodaGradeLabel = new JLabel();
        notesTextArea = new JTextArea();
        notesLabel = new JLabel();
        addButton = new JButton();
        backButton = new JButton();
        sp = new JScrollPane(notesTextArea, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED, ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        JPanel editFrame = this;

        library = l;

        directions.setHorizontalAlignment(SwingConstants.CENTER);
        directions.setText("Edit the composition below.");

        titleLabel.setText("Title:");

        titleField.setText(edit.getTitle());
        titleField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }

            private void titleFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
                // TODO add your handling code here:
                // Add search function here OR on a different frame
            }//GEN-LAST:event_titleFieldActionPerformed
        });

        composerLabel.setText("Composer:");
        composerField.setText(edit.getComposer());

        arrangerLabel.setText("Arranger: ");
        arrangerField.setText(edit.getArranger());

        publisherLabel.setText("Publisher:");
        publisherField.setText(edit.getPublisher());

        vbodaGradeLabel.setText("VBODA Grade: ");
        vbodaGradeField.setText(edit.getVbodaGrade().toString());

        notesLabel.setText("Notes:");
        notesTextArea.setText(edit.getNotes());
        notesTextArea.setLineWrap(true);
        notesTextArea.setWrapStyleWord(true);
        
        addButton.setText("Save");
        addButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                try {
                    addButtonActionPerformed(evt);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

            private void addButtonActionPerformed(ActionEvent evt) throws Exception
            {
                if(Integer.parseInt(vbodaGradeField.getText()) < 0 || Integer.parseInt(vbodaGradeField.getText()) > 6)
                {
                    JOptionPane.showMessageDialog(editFrame, "Invalid input", "ERROR", JOptionPane.ERROR_MESSAGE);
                    vbodaGradeField.setText("0");
                }

                else
                {
                    Composition c = new Composition(titleField.getText(),
                                                                composerField.getText(),
                                                                arrangerField.getText(),
                                                                publisherField.getText(),
                                                                Integer.parseInt(vbodaGradeField.getText()),
                                                                notesTextArea.getText());
                    if(ifAdd)
                    {
                        library.append(c);
                    }
                    else
                    {
                        library.replace(index, c);
                        ViewFrame.resetResults();
                        Object[][] data = new Object [ViewFrame.numSearchResults()][6];
                        ViewFrame.populateTable(ViewFrame.retrieveData(data));
                    }
                    library.sortByTitle();

                    EditSummaryFrame esFrame = new EditSummaryFrame(c, library);
                    JFrame frame = new JFrame("EditConfirmationFrame");
            
                    frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frame.getContentPane().add(esFrame, BorderLayout.CENTER);
                    frame.pack();
                    frame.setVisible(true);
                }
            }
        });

        backButton.setText("Cancel");
        backButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                backButtonActionPerformed(evt);
            }

            private void backButtonActionPerformed(ActionEvent evt) 
            {
                JComponent comp = (JComponent)evt.getSource();
                Window win = SwingUtilities.getWindowAncestor(comp);
                win.dispose();
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(directions))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(vbodaGradeLabel)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vbodaGradeField, GroupLayout.PREFERRED_SIZE, 90, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(notesLabel)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sp, GroupLayout.PREFERRED_SIZE, 363, GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(composerLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(composerField))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(titleLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(titleField, GroupLayout.PREFERRED_SIZE, 371, GroupLayout.PREFERRED_SIZE))))
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(arrangerLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(arrangerField, GroupLayout.PREFERRED_SIZE, 345, GroupLayout.PREFERRED_SIZE))
                                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(publisherLabel)
                                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(publisherField, GroupLayout.PREFERRED_SIZE, 347, GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(backButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(directions)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(composerLabel)
                    .addComponent(composerField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(arrangerLabel)
                    .addComponent(arrangerField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(publisherLabel)
                    .addComponent(publisherField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(vbodaGradeLabel)
                    .addComponent(vbodaGradeField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(notesLabel)
                    .addComponent(sp, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(backButton))
                .addContainerGap())
        );
    }
}
